language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3.3" ]; then phpunit --self-update; fi;'

script:
    - phpunit